import Link from "next/link";
import styles from "./privacy.module.css";

export const metadata = {
  title: "Informativa privacy — Bozza | Mitha Creative",
  description: "Bozza dell’informativa privacy di Mitha Creative, in attesa dei dati del titolare e dei fornitori.",
  robots: { index: false, follow: false },
};

export default function PrivacyPage() {
  return (
    <article className={styles.page}>
      <header><p className={styles.eyebrow}>Privacy / Documento in preparazione</p><h1>Informativa sul trattamento dei dati personali</h1><p className={styles.notice}><strong>Bozza da completare.</strong> Questo documento non è ancora l’informativa definitiva. I campi tra parentesi quadre devono essere compilati e le modalità di trattamento confermate prima di attivare il modulo.</p></header>
      <section><h2>1. Titolare del trattamento</h2><p>[Nome e cognome o ragione sociale del titolare], con sede in [indirizzo completo], opera attraverso il sito Mitha Creative. Per le richieste relative ai dati personali: [contatto privacy].</p><p>[Indicare i contatti del responsabile della protezione dei dati, se nominato; altrimenti eliminare questa riga.]</p></section>
      <section><h2>2. Dati raccolti</h2><p>Il modulo progetto raccoglie nome, indirizzo email, servizi selezionati, descrizione del progetto e fascia di budget indicativa. Il messaggio può contenere altri dati che scegli di comunicare, ad esempio il collegamento al tuo sito. Evita di inserire dati sensibili non necessari alla richiesta.</p><p>Scrivendo direttamente via email vengono trattati il tuo indirizzo e il contenuto della conversazione. La navigazione può generare dati tecnici, come indirizzi IP e registri del server: [descrivere quelli effettivamente raccolti dal fornitore di hosting].</p></section>
      <section><h2>3. Finalità e basi giuridiche</h2><p>I dati delle richieste di progetto sono utilizzati per rispondere, valutare le esigenze e organizzare il confronto richiesto. Per le attività precontrattuali richieste dall’interessato, la base giuridica proposta è l’articolo 6, paragrafo 1, lettera b), del GDPR.</p><p>[Verificare e indicare separatamente le basi giuridiche per richieste generiche, sicurezza del sito, adempimenti obbligatori e ulteriori finalità effettive.]</p><p>La presa visione dell’informativa non costituisce un consenso all’invio di marketing. [Confermare se vengono effettuate comunicazioni promozionali e, in tal caso, descriverne separatamente finalità, base giuridica e modalità di opposizione o revoca.]</p></section>
      <section><h2>4. Conferimento dei dati</h2><p>Il conferimento è volontario. I campi contrassegnati da un asterisco nel modulo sono richiesti per gestire la domanda: in loro assenza non è possibile inviarla attraverso il modulo. Per il budget è disponibile l’opzione “Non so ancora”. Puoi anche contattarci direttamente via email.</p></section>
      <section><h2>5. Destinatari e fornitori</h2><p>I dati possono essere trattati dal personale autorizzato e dai fornitori necessari a gestire il sito e le comunicazioni, secondo i rispettivi ruoli e gli accordi applicabili.</p><p>[Indicare provider di hosting, servizio di posta elettronica e ogni altro fornitore effettivo, con ruolo e categorie di dati trattati. Nel codice attuale è configurato un trasporto SMTP Gmail: verificare il servizio concretamente utilizzato in produzione.]</p></section>
      <section><h2>6. Trasferimenti fuori dallo Spazio economico europeo</h2><p>[Verificare la localizzazione dei fornitori e degli eventuali subfornitori. Specificare se vi sono trasferimenti, i Paesi coinvolti, il meccanismo applicabile e come ottenere informazioni sulle garanzie. Non presumere che tutti i dati rimangano nell’Unione europea.]</p></section>
      <section><h2>7. Conservazione</h2><p>[Definire il periodo concreto o criteri sufficientemente precisi per richieste senza seguito, trattative, clienti e registri tecnici. Indicare anche come vengono gestiti casella email, backup ed eventuali obblighi di conservazione.]</p></section>
      <section><h2>8. Diritti delle persone</h2><p>Nei casi e alle condizioni previsti dal GDPR, puoi richiedere accesso ai dati, rettifica, cancellazione, limitazione e portabilità, nonché opporti ai trattamenti fondati sul legittimo interesse. Quando il trattamento si basa sul consenso, puoi revocarlo senza pregiudicare la liceità del trattamento precedente.</p><p>Per esercitare i diritti scrivi a [contatto privacy]. Puoi inoltre presentare reclamo al <a href="https://www.garanteprivacy.it/">Garante per la protezione dei dati personali</a> o all’autorità di controllo competente.</p></section>
      <section><h2>9. Cookie e contenuti esterni</h2><p>[Completare dopo aver verificato il sito pubblicato.] Il progetto contiene riferimenti a YouTube e alla libreria Iconify, collegamenti social, un contenitore Elfsight e il badge esterno della Green Web Foundation nella pagina sostenibilità. Occorre distinguere i servizi realmente caricati dai semplici collegamenti e verificare dati tecnici, cookie, archiviazione locale ed eventuali consensi richiesti.</p><p>Il tema chiaro/scuro usa una preferenza locale tramite next-themes. [Confermare le tecnologie effettivamente attive, la loro durata e l’eventuale presenza di analytics o marketing; predisporre, se necessaria, un’informativa cookie coordinata.]</p></section>
      <section><h2>10. Decisioni automatizzate e aggiornamenti</h2><p>[Confermare l’assenza o descrivere l’esistenza di decisioni automatizzate o profilazione rilevanti.]</p><p>Ultimo aggiornamento: [data di approvazione della versione definitiva].</p></section>
      <aside className={styles.sources}><h2>Riferimenti per completare la bozza</h2><p><a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj/?locale=it">Regolamento UE 2016/679, in particolare articoli 6 e 13</a> e <a href="https://www.garanteprivacy.it/web/guest/home/docweb/-/docweb-display/docweb/8981258">indicazioni del Garante sull’informativa</a>. Le parti tra parentesi devono essere verificate rispetto all’organizzazione e ai servizi effettivamente utilizzati.</p></aside>
      <Link href="/inizia-il-progetto" className={styles.back}>Torna al modulo progetto</Link>
    </article>
  );
}
