import Hero from "./components/Hero/Hero";
import Marquee from "./components/Marquee/marquee";
import Image from "next/image";
import { Icon } from "@iconify/react";
import Cta from "./components/Cta/Cta";
import LenisScroll from "./components/LenisiScroll/LenisScroll";
import CtaLight from "./components/Cta/CtaLight";

export const metadata = {
  title: "Mitha creative",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <LenisScroll />
      <Hero />
      <Marquee />
      <section className="grid grid-cols-1 lg:grid-cols-2 my-10 w-[90%] mx-auto  lg:py-20 items-center gap-y-6 lg:gap-x-8">
        <div className="relative w-[300px] lg:w-full  lg:h-[550px] aspect-square">
          <Image
            src="/assets/astronautaweb2.webp"
            alt="astronauta web"
            fill
            className="object-contain rotate-[-25deg]"
          />
        </div>
        <div className="flex flex-col gap-y-8">
          <h2 className="text-4xl font-bold lg:text-5xl text-primary dark:text-white">
            Web design & Brand Identity
          </h2>
          <p className="text-primary dark:text-white">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit
          </p>
          <p className="text-primary/75 dark:text-white/75">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat.
          </p>
          <ul className="grid gap-4 lg:grid-flow-col lg:grid-rows-3">
            <li className="flex items-center gap-1">
              <Icon
                icon="mdi:star-four-points"
                width="1rem"
                height="1rem"
                className="text-primary dark:text-white"
              />
              <span className="ml-2">Lorem ipsum dolor sit amet</span>
            </li>
            <li className="flex items-center gap-1">
              <Icon
                icon="mdi:star-four-points"
                width="1rem"
                height="1rem"
                className="text-primary dark:text-white"
              />
              <span className="ml-2">Lorem ipsum dolor sit amet</span>
            </li>
            <li className="flex items-center gap-1">
              <Icon
                icon="mdi:star-four-points"
                width="1rem"
                height="1rem"
                className="text-primary dark:text-white"
              />
              <span className="ml-2">Lorem ipsum dolor sit amet</span>
            </li>
            <li className="flex items-center gap-1">
              <Icon
                icon="mdi:star-four-points"
                width="1rem"
                height="1rem"
                className="text-primary dark:text-white"
              />
              <span className="ml-2">Lorem ipsum dolor sit amet</span>
            </li>
            <li className="flex items-center gap-1">
              <Icon
                icon="mdi:star-four-points"
                width="1rem"
                height="1rem"
                className="text-primary dark:text-white"
              />
              <span className="ml-2">Lorem ipsum dolor sit amet</span>
            </li>
            <li className="flex items-center gap-1">
              <Icon
                icon="mdi:star-four-points"
                width="1rem"
                height="1rem"
                className="text-primary dark:text-white"
              />
              <span className="ml-2">Lorem ipsum dolor sit amet</span>
            </li>
          </ul>
          <Cta link="/">Get started</Cta>
        </div>
      </section>
      <section className="w-[90%] mx-auto flex flex-col gap-6">
        <div className="flex justify-center w-full lg:text-center">
          <h2 className="text-4xl font-bold lg:text-5xl text-primary dark:text-white">
            Features are more helpful <br /> to create creative shapes as well
          </h2>
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-5 w-full lg:h-[500px] gap-4 min-h-auto">
          <div className="rounded-[20px] h-[100px] lg:h-auto bg-primary dark:bg-purple relative">
            <Image
              src="/assets/stars.svg"
              fill
              className="object-cover w-full h-full "
              alt=""
            />
          </div>
          <div className="rounded-[20px] bg-purple/35 dark:bg-white p-6 flex flex-col h-full justify-between">
            <div className="text-2xl font-bold text-primary">01</div>
            <div className="flex flex-col gap-1">
              <h3 className="text-xl font-bold text-primary">Research</h3>
              <p className="text-primary/80 leading-[1.3]">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              </p>
            </div>
          </div>
          <div className="rounded-[20px] bg-purple/35 dark:bg-white p-6 flex flex-col h-full justify-between">
            <div className="text-2xl font-bold text-primary">02</div>
            <div className="flex flex-col gap-1">
              <h3 className="text-xl font-bold text-primary">Plan & Sketch</h3>
              <p className="text-primary/80 leading-[1.3]">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              </p>
            </div>
          </div>{" "}
          <div className="rounded-[20px] bg-purple/35 dark:bg-white p-6 flex flex-col h-full justify-between">
            <div className="text-2xl font-bold text-primary">03</div>
            <div className="flex flex-col gap-1">
              <h3 className="text-xl font-bold text-primary">Customize</h3>
              <p className="text-primary/80 leading-[1.3]">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              </p>
            </div>
          </div>{" "}
          <div className="rounded-[20px] bg-purple/35 dark:bg-white p-6 flex flex-col h-full justify-between">
            <div className="text-2xl font-bold text-primary">04</div>
            <div className="flex flex-col gap-1">
              <h3 className="text-xl font-bold text-primary">User Testing</h3>
              <p className="text-primary/80 leading-[1.3]">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              </p>
            </div>
          </div>{" "}
        </div>
      </section>
      <section className="flex flex-col gap-6 my-10 bg-primary dark:bg-white">
        <div className="flex flex-wrap items-end w-[90%] mx-auto h-auto justify-between pt-20 pb-10 gap-y-6">
          <h2 className="text-4xl font-bold text-white lg:text-5xl dark:text-primary">
            Dai un’occhiata ai <br /> nostri progetti creativi
          </h2>
          <CtaLight link="/">Get Started</CtaLight>
        </div>
        <section className="grid gap-6 w-[90%] mx-auto mb-20">
          {/* Riga 1: Colonna stretta sinistra */}
          <div className="grid grid-cols-1 gap-6 lg:grid-cols-12">
            <div className="relative col-span-12 lg:col-span-4 h-[450px]">
              <Image
                src="/assets/illustrazioni5_new.webp"
                alt=""
                fill
                className="object-cover w-full h-full rounded-[20px]"
              />
            </div>
            <div className="col-span-12 lg:col-span-8 h-[450px] relative">
              <Image
                src="/assets/lou_portfolio.png"
                alt=""
                fill
                className="object-cover w-full h-full rounded-[20px]"
              />
            </div>
          </div>

          {/* Riga 2: Colonna stretta destra */}
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-12">
            <div className="col-span-12 lg:col-span-8 h-[450px] relative">
              <Image
                src="/assets/miao_home.png"
                alt=""
                fill
                className="object-cover w-full h-full rounded-[20px]"
              />
            </div>
            <div className="relative col-span-12 lg:col-span-4 h-[450px]">
              <Image
                src="/assets/logoDesign2.webp"
                alt=""
                fill
                className="object-cover w-full h-full rounded-[20px]"
              />
            </div>
          </div>

          {/* Riga 3: Colonna stretta sinistra */}
          <div className="grid grid-cols-1 gap-4 lg:grid-cols-12">
            <div className="relative col-span-12 lg:col-span-4 h-[450px]">
              <Image
                src="/assets/campagne10.webp"
                alt=""
                fill
                className="object-cover w-full h-full rounded-[20px]"
              />
            </div>
            <div className="col-span-12 lg:col-span-8 h-[450px] relative">
              <Image
                src="/assets/tendeclissi_main.png"
                alt=""
                fill
                className="object-cover w-full h-full rounded-[20px]"
              />
            </div>
          </div>
        </section>
      </section>
      <section className="h-screen my-20 "></section>
    </>
  );
}
