import PageClient from "./page.client";

export const metadata = {
  title: "Mitha creative",
  description: "Generated by create next app",
};

export default function Home() {
  return <PageClient />;
}
