import React from "react";
import HeroPage from "../components/Hero/HeroPage";
import Link from "next/link";
export const metadata = {
  title: "Mitha creative - Contatti",
  description: "Generated by create next app",
};
function contatti() {
  return (
    <div>
      <HeroPage>
        <h1 className="text-6xl text-primary dark:text-white">Contatti</h1>
        <p className="text-primary uppercase text.2xl">
          vuoi maggiori informazioni?
        </p>
      </HeroPage>
      <section className="h-screen my-20 w-[90%] mx-auto">
        <div className="flex flex-col items-center max-w-3xl gap-2 py-10 mx-auto text-center">
          <h2 className="text-xl lg:text-3xl text-primary dark:text-white">
            Compila il modulo per entrare in contatto con noi <br />e
            condividere la tua storia.
          </h2>
          <p className="text-base lg:text-xl text-primary dark:text-white fxl:text-2xl">
            Le nostre risposte non tarderanno: dal lunedì al venerdì,
            solitamente rispondiamo entro 72 ore dall&apos;arrivo
            dell&apos;email. Le distanze geografiche non rappresentano alcun
            ostacolo: collaboriamo con clienti provenienti da ogni angolo
            d&apos;Italia e non solo.
          </p>
        </div>
      </section>
    </div>
  );
}

export default contatti;
