import React from "react";
import ServiziClient from "./page.client";
export const metadata = {
  title: "Mitha creative - Servizi",
  description: "Generated by create next app",
};
function Servizi() {
  return (
    <div>
      <ServiziClient />
    </div>
  );
}

export default Servizi;
